### ISSUE TITLE
Document T&P website (Frontend)

### ISSUE THREAD

**Issue by vish-rt** [tcet-opensource/documentation#34]
Document the workflow of T&P site, the work done by the team from low fidelity diagram to frontend coding till date.

**Comment by JayeshVP24** [comment]
# Header & Navbar Redesigned
- The previous header and navbar were very clunked. 
- Header and Navbar are supposed to be easy to use and are very important for User Experience (UX)
- We redesigned the header and navbar with complete responsiveness to make it look clean and extremely easy to use
# Statistics
- We redesigned how statistics are displayed on the website
- Statistics are important to show credibility of our services.
- Showing statistics properly will give us an edge of transparency
# Recruiters
- We are showing top recruiters in the right in the main page above hero section
- This shows any students or parents visiting our website that many good companies visit our college for placements
# Showing more credibility
- We also display awards received by TnP Cell of college
- Showing student achievements
- showing top placed students
- showing testimonials of not just companies but also students
# Training Page
- We have increased the focus from just pre-placements programs to every TnP program which helps students learn something
- We are also displaying the professional bodies under TnP cell who have their own set of sessions and programs and help students learn and grow their skills
- We have special mention of TCET open source because contributing to open source will anyone a high edge over competition in the market. Also the fact that college level OSS org apart from TCET only exist in IIT Mumbai.
- We also mention the huge events happening in our college done by various Professional Bodies of TnP.
- These all shows how well we train our students to be industry ready and achieve edge over competition
# Placements & Internship Page
- Here we changed how we display the companies list. We include their logos which are under creative commons license and can be used by anyone.
- We also show statistics of all placed students and companies for proper transparency
# Industry Interaction & Events
- Many industries visit our campus and talk to our students and interact with them. We display these interactions and experience of the industry expert in our website
- We also display all the events done by TnP such as SDP, CCP, ACT etc
- We have a page for each of this event with specific information in depth and photo and stats.
- These all will show prospective companies how we are always active and have high skilled are students are getting and will influence them to reach to us

**Comment by JayeshVP24** [comment]
# Run Locally

## 🧞 Commands

Install yarn globally first | `npm install -g yarn` 

All commands are run from the root of the project, from a terminal:

| Command                | Action                                           |
| :--------------------- | :----------------------------------------------- |
| `yarn`          | Installs dependencies                            |
| `yarn dev`          | Starts local dev server at `localhost:3000`      |
| `yarn build`        | Build your production site to `./dist/`          |
| `yarn preview`      | Preview your build locally, before deploying     |
| `yarn astro ...`    | Run CLI commands like `astro add`, `astro check` |
| `yarn astro --help` | Get help using the Astro CLI                     |

## Steps to run after a Pull / Merge
1. `yarn` to install all dependencies
2. `yarn dev` run local dev environment

**Comment by demonkillerr** [comment]
This issue needs to be completed on priority basis. Kindly work on the mentioned branch `34-document-tnp-website`.

**Comment by himanshu-03** [comment]
### T&P Website

Assigned to @NikitaSShukla 
> - [ ] About TNP Website
> - [ ] Getting Started
> - [ ] Header
> - [ ] Hero

Assigned to @aryadubey03 
> - [ ] Event Page Component
> - [ ] Footer
> - [ ] Header
> - [ ] Hero

Assigned to @SakshiPorwal 
> - [ ] Industry Interaction
> - [ ] Internships
> - [ ] Placed Students
> - [ ] Awards

Assigned to 
> - [ ] Testimonials
> - [ ] Top Placed STudents
> - [ ] Top Recruiters
> - [ ] Training

- [ ] Placement

**Comment by himanshu-03** [comment]
@Jayesh if you can ask someone from the web team to look at some of the components documented for the T&P website?

Completed Components as of now: 

Student Awards
Testimonials
Internships
Industry Interaction
Training

**Comment by himanshu-03** [comment]
Completed Sections

- [x] Training
- [x] Placement

**Comment by aryadubey03** [comment]
Completed Sections

- [ ] Student Awards
- [ ] Testimonials
- [ ] Internships
- [ ] Industry Interaction
- [ ] Header

**Comment by himanshu-03** [comment]
@JayeshVP24 tech stacks used?

**Comment by JayeshVP24** [comment]
> @JayeshVP24 frontend tech stacks used?

Astro - Javascript Framework
TailwindCSS - CSS Framework
Swiper - Swipers functionality
Strapi - Backend CMS

**Comment by Mahitej28** [comment]
> > @JayeshVP24 frontend tech stacks used?
> 
> Astro - Javascript Framework TailwindCSS - CSS Framework Swiper - Swipers functionality Strapi - Backend CMS

Would Strapi come in frontend Tech Stack or it would be written in the backend?

**Comment by JayeshVP24** [comment]
> > > @JayeshVP24 frontend tech stacks used?
> > 
> > Astro - Javascript Framework TailwindCSS - CSS Framework Swiper - Swipers functionality Strapi - Backend CMS
> 
> Would Strapi come in frontend Tech Stack or it would be written in the backend?

Ah opps, you're right. Strapi would come in backend!

**Comment by Mahitej28** [comment]
Completed Section

- [ ] Tech Stacks

**Comment by NikitaSShukla** [comment]
Completed Sections:

- [ ] About T&P
- [ ] Getting Started
- [ ] Hero
